### ISSUE TITLE
Switch between namespaces with dropdown menu

### ISSUE THREAD

**Issue by shintoo** [FlaSpaceInst/EZ-RASSOR#221]
on startup and on switch (or more often):
- find instances via rostopic list
- populate combobox
- on combobox select, d/c from last, connect to new

**Comment by tgsachse** [comment]
This is accomplished by switching namespaces. Will need to check if possible to recalibrate/restart subscribers using different namespaces (because restarting the node has proven to be impossible/extremely difficult to do correctly). This will also mean that the launch file for the dashboard and any launch files that optionally launch the dashboard must launch the dashboard in the root "/" namespace and then namespaces will be appended to strings passed to the subscribers both at launch and every time the ezrassor is swapped out.

**Comment by tgsachse** [comment]
General plan for how to do this:
- periodically get list of node names from ros master (probably during ros::spin)
- parse this list, remove any that dont contain "ezrassor", then chop off the least significant portion of name (the actual node name, leaving behind only the namespace)
- save this list of namespaces as a QStringList in topic translator, SIGNAL that a new list is ready and pass a reference to the list
- signal links to slot in main window. Main window slot waits for a new QStringList, then it dumps contents of current namespace combo box and loads in new list of strings.

To switch namespaces:
- new namespace selected from combo box. Combo box SIGNALs the new text.
- Signal caught by slot on topic translator, which updates appropriate topic strings?, then flips some sort of indicator boolean to tell ros::spin to die?
- ros::spin dies and returns control to large containing while loop. This forces subscribers out of scope, so they are deleted
- reenter loop, rebuild subscribers with new names
- re-enter ros::spin (modified)

Code looks something like this:
void run() {
  while true:
    sub = subscriber(my_topic)
    while not told to break:
       run all the subscribers
       check for new strings
    break out of big loop if necessary
}

**Comment by tgsachse** [comment]
Clear log when switching namespaces
Filter log by current namespace
