### ISSUE TITLE
Print log from /rosout_agg with options

### ISSUE THREAD

**Issue by shintoo** [FlaSpaceInst/EZ-RASSOR#222]

**Comment by tgsachse** [comment]
One approach is to redirect stdout to text box. Feasibility still being explored.

**Comment by tgsachse** [comment]
current plan: Print msgs from rosout_agg. Filter messages based on both namespace and a package whitelist. Store package whitelist with resources, load on launch and hash for lookup speed. Upon receiving a new message, check against namespace, then check against whitelist. If both checks pass, print msg along with severity and package name:

[INFO] [ezrassor_controller_server] Firing up the controller server.
[INFO] [ezrassor_autonomous_control] Full autonomy enabled.

Because of how rosout works, these messages will also end up in the normal ros logs, which is sort of a 2 birds 1 stone approach.

**Comment by tgsachse** [comment]
When namespace switches, clear the text box.

**Comment by tgsachse** [comment]
Remaining:
- Implement namespace switching (separate issue)
- Add log messages to different nodes
- Add a separate error for broken file IO
- Remove check boxes in GUI
